/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Challenge: typeof import('./src/components/Challenge.vue')['default']
    Chatbot: typeof import('./src/components/challenge/Chatbot.vue')['default']
    Details: typeof import('./src/components/challenge/Details.vue')['default']
    Entry: typeof import('./src/components/challenge/Entry.vue')['default']
    Feedback: typeof import('./src/components/challenge/Feedback.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Message: typeof import('./src/components/challenge/Message.vue')['default']
    Post: typeof import('./src/components/challenge/Post.vue')['default']
    Results: typeof import('./src/components/challenge/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
